travel/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api.views import changeLanguage
from api.views import CategoryMainViewSet, CategorySubViewSet, LocationViewSet, LocationGalleryViewSet, TripViewSet, StyleViewSet

router = DefaultRouter()

router.register('api_category_main', CategoryMainViewSet)
router.register('api_category_sub', CategorySubViewSet)
router.register('api_location', LocationViewSet)
router.register('api_location_gallery', LocationGalleryViewSet)

router.register('api_trip', TripViewSet)
router.register('api_trip_style', StyleViewSet)


app_name = 'api'

urlpatterns = [
    path('', include(router.urls), name="api_location"),
    path('change/<slug:language>', changeLanguage, name="change-language"),

]

travel/location/urls.py
from django.urls import include, path
from . import views

app_name = 'location'

urlpatterns = [
    path('search/', views.search, name='search'),

    # path('', views.LocationListView.as_view(), name='location_list'),
    path('', views.location_list, name='location_list'),
    path('detail/<int:pk>/', views.LocationDetail, name='location_detail'),
]

travel/staff/urls.py
from django.urls import include, path
# from hotel.views import 
# from ManageHotels.views import ChartData,ChartView

from staff.views import (
    staff, location, category, question, season, other, style, landmark, contact, hotel,
    partner,
    )

# app_name = 'staff'

urlpatterns = [

    path('', staff.home_view, name='home_admin'),

    path('location/', include(([
        path('', location.location_view, name='location_view'),
        path('image/', location.LocationGalleryCreateView.as_view(), name='location_image'),
        path('create/', location.location_create_view, name='location_create'),
        path('detail/<int:pk>/', location.LocationDetail, name='location_detail'),
        # path('update/<int:pk>/', location.location_update_view, name='location_update'),
        path('update/<int:pk>/', location.LocationUpdateView.as_view(), name='location_update'),
        path('delete/<int:pk>/', location.LocationDeleteView.as_view(), name='location_delete'),
    ], 'staff'), namespace='location_admin')),    


    path('category/', include(([
        path('', category.CategoryListView.as_view(), name='category_view'),
        path('create/', category.CategoryCreateView.as_view(), name='category_create'),
        path('update/<int:pk>/', category.CategoryUpdateView.as_view(), name='category_update'),
        path('delete/<int:pk>', category.CategoryDeleteView.as_view(), name='category_delete'),
    ], 'staff'), namespace='category_admin')),    


    path('question/', include(([
        path('', question.QuizListView.as_view(), name='quiz_change_list'),
        path('quiz/add/', question.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/results/view', question.results_view, name='results_view'),
        path('quiz/<int:pk>/', question.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', question.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', question.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', question.question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', question.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', question.QuestionDeleteView.as_view(), name='question_delete'),
        path('generate/', question.generate_report, name='generate_report'),
    ], 'staff'), namespace='question_admin')),

    # path('other/', other.other_staff, name='other_staff'),
    path('contact/', other.contact_staff, name='contact_staff'),


    # path('season/', include(([
    #     path('create/', season.SeasonCreateView.as_view(), name='season_create'),
    #     path('update/<int:pk>/', season.SeasonUpdateView.as_view(), name='season_update'),
    #     path('delete/<int:pk>/', season.SeasonDeleteView.as_view(), name='season_delete'),
    # ], 'staff'), namespace='season_admin')),

    # path('style/', include(([
    #     path('create/', style.StyleCreateView.as_view(), name='style_create'),
    #     path('update/<int:pk>/', style.StyleUpdateView.as_view(), name='style_update'),
    #     path('delete/<int:pk>/', style.StyleDeleteView.as_view(), name='style_delete'),
    # ], 'staff'), namespace='style_admin')),


    # path('landmark/', include(([
    #     path('create/', landmark.LandmarkCreateView.as_view(), name='landmark_create'),
    #     path('update/<int:pk>/', landmark.LandmarkUpdateView.as_view(), name='landmark_update'),
    #     path('delete/<int:pk>/', landmark.LandmarkDeleteView.as_view(), name='landmark_delete'),
    # ], 'staff'), namespace='landmark_admin')),


    path('contact/', include(([
        path('create/', contact.ContactCreateView.as_view(), name='contact_create'),
        path('update/<int:pk>/', contact.ContactUpdateView.as_view(), name='contact_update'),
        path('delete/<int:pk>/', contact.ContactDeleteView.as_view(), name='contact_delete'),
    ], 'staff'), namespace='contact_admin')),


     path('hotel/', include(([
     # path('', views.showhotels, name='showhotel'),
        path('', hotel.home, name='home'),

        path('hotel', hotel.showhotels, name='hotel_view'),
        path('hotel/create', hotel.HotelCreateView.as_view(), name='hotel_create'),
        path('hotel/update/(<pk>[0-9]+)', hotel.HotelUpdateView.as_view(), name='hotel_update'),
        path('hotel/delete/(<pk>[0-9]+)', hotel.HotelDeleteView.as_view(), name='hotel_delete'),

          # Bookings
        path('hotel/bookings/(<pk>[0-9]+)', hotel.showreservations, name='hotel_reservations'),
        path('hotel/bookings/delete/(<pk>[0-9]+)', hotel.cancelbooking, name='booking_remove'),
          
          
          # Room
        path('hotel/room/(<pk>[0-9]+)', hotel.managehotel, name='room_view'),
        path('hotel/rooms/create/(<pk>[0-9]+)', hotel.RoomCreateView.as_view(), name='room_create'),
        path('hotel/rooms/update/(<pk>[0-9]+)', hotel.RoomUpdateView.as_view(), name='room_update'),
        path('hotel/rooms/delete/(<pk>[0-9]+)', hotel.RoomDeleteView.as_view(), name='room_delete'),
          
          # Photo
        path('hotel/photo/(<id>[0-9]+)', hotel.showphotodash, name='photo_view'),
        path('hotel/photo/upload(<id>[0-9]+)', hotel.BasicUploadView.as_view(), name='photo_upload'),
        path('hotel/photo/delete/(<id>[0-9]+)', hotel.deletePhoto, name='photo_delete'),
        path('hotel/photo/thumbnail(<id>[0-9]+)', hotel.editThumbnail, name='editThumb'),

          # Chart
        path('charts/(<id>[0-9]+)/', hotel.ChartView.as_view(), name = 'partner_charts'),
        path('chart/data/(<id>[0-9]+)/', hotel.ChartData.as_view()),


        path('zxc', partner.displayDash, name='displayDash'),

        path('partners', partner.showPartners, name='showpartners'),
        path('partners/remove/(<id>[0-9]+)', partner.removePartner, name='removepartner'),

        path('proposals', partner.showProposals, name='showproposals'),
        path('proposals/accept/(<id>[0-9]+)', partner.acceptProposals, name='acceptproposal'),
        path('proposals/decline/(<id>[0-9]+)', partner.declineProposals, name='declineproposal'),
        
        path('partner/checkstatus', partner.checkstatus, name='proposal_check'),
    
     ], 'staff'), namespace='hotel_admin')),

]

travel/travel/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from general.views import home_view

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
	must_authenticate_view,
)

from question.views import question, active
from staff.views import staff 




urlpatterns = [

    path('api/', include('api.urls')),

    path('login/', login_view, name="login"),
    # path('logout/', logout_view, name="logout"),
	path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),


    path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/signup/', question.SignUpView.as_view(), name='signup'),
    path('accounts/signup/active/', active.ActiveSignUpView.as_view(), name='active_signup'),
    path('accounts/signup/staff/', staff.StaffSignUpView.as_view(), name='staff_signup'),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    
] 
urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),


    path('', home_view, name="home"),
    path('', include('api.urls')),
    path('blog/', include('blog.urls', 'blog')),
    path('trip/', include('trip.urls'), name='trip'),
    path('location/', include('location.urls'), name='location'),
    path('question/', include('question.urls')),
    path('contact/', include('general.urls')),
    path('hotel/', include('hotel.urls'), name="hotel"),
    path('account/', account_view, name="account"),
    path('staff/', include('staff.urls'), name="staff"),

)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travel/staff/models.py
from django.db import models

# Create your models here.

travel/staff/forms.py
from django import forms
from hotel.models import Photo

# Using djangos Model forms to create a form using a model.


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['path', ]

travel/location/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, DeleteView, UpdateView

from location.models import Location, LocationGallery
from location.forms import LocationCreateForm
from location.filters import LocationFilter
from helper.location import get_location_return_object_image

# Search
def search(request):
    location_list = Location.objects.all()
    location_filter = LocationFilter(request.GET, queryset=location_list)

    data = {
        # 'max': max,
        # 'min': min,
        # 'cost_list': cost_list,
        'filter': location_filter,
    }
    
    return render(request, 'location/location_search.html', data)



class LocationView(ListView):
    template_name = 'location/location_list.html'
    context_object_name = 'location_image'
    model = LocationGallery



def location_list(request):

    locations = Location.objects.all()

    # google = Location.objects.get(name='น้ำตกเอราวัณ')
    # location_image = google.location_image.all()
    # print(location_image)

    
    locations_images = []
    images_list = LocationGallery.objects.all()
    # for item in images_list:
    #     locations_images.append(item)

    # for item in locations:
    #     location_line = []
    #     location_line.append(item.name)

    # for item in locations:
    #     # location_line = []
    #     location_line = LocationGallery.objects.filter(location_gallery=item)
    #     if not location_line[0]:
    #         locations_images.append("null")
    #     else:    
    #         locations_images.append(location_line[0])

    location_list = []
    for item in locations:
        location_line = []
        location_line.append(item)
        location_line.append(LocationGallery.objects.filter(location_gallery=item))
        location_list.append(location_line)


    data = {
        'locations': locations,
        'location_list': location_list,
    }

    return render(request, "location/location_list.html", data)



def LocationDetail(request, pk):
    location = Location.objects.filter(pk=pk)
    location = location[0]

    images = get_location_return_object_image(location)

    data = {
        'location': location,
        'images': images,
    }

    return render(request, 'location/location_detail.html', {'data':data})

travel/staff/views/category.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, DeleteView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from question.decorators import staff_required
from location.models import CategorySub


@method_decorator([login_required, staff_required], name='dispatch')
class CategoryListView(ListView):
    model = CategorySub
    context_object_name = 'categorys'
    template_name = 'staff/category/category_view.html'

    
@method_decorator([login_required, staff_required], name='dispatch')
class CategoryCreateView(CreateView):
    model = CategorySub
    context_object_name = 'category'
    template_name = 'staff/category/category_create.html'
    fields = ['name', 'category_main']

    def get_success_url(self):
        return reverse_lazy('category_admin:category_view')


@method_decorator([login_required, staff_required], name='dispatch')
class CategoryUpdateView(UpdateView):
    model = CategorySub
    context_object_name = 'category'
    template_name = 'staff/category/category_update.html'
    fields = ['name', 'category_main']

    def get_success_url(self):
        return reverse_lazy('category_admin:category_view')


@method_decorator([login_required, staff_required], name='dispatch')
class CategoryDeleteView(DeleteView):
    model = CategorySub
    context_object_name = 'category'
    template_name = 'staff/category/category_delete.html'
    success_url = reverse_lazy('category_admin:category_view')

travel/staff/views/contact.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, DeleteView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from question.decorators import staff_required
from general.models import Contact, ContactDetail


@method_decorator([login_required, staff_required], name='dispatch')
class ContactCreateView(CreateView):
    model = ContactDetail
    context_object_name = 'contact'
    template_name = 'staff/contact/contact_create.html'
    fields = ['name', 'contact', 'phone', 'email', 'address']
    def get_success_url(self):
        return reverse_lazy('contact_staff')


@method_decorator([login_required, staff_required], name='dispatch')
class ContactUpdateView(UpdateView):
    model = ContactDetail
    context_object_name = 'contact'
    template_name = 'staff/contact/contact_update.html'
    fields = ['name', 'contact', 'phone', 'email', 'address']
    def get_success_url(self):
        return reverse_lazy('contact_staff')


@method_decorator([login_required, staff_required], name='dispatch')
class ContactDeleteView(DeleteView):
    model = ContactDetail
    context_object_name = 'contact'
    template_name = 'staff/contact/contact_delete.html'
    def get_success_url(self):
        success_url = reverse_lazy('contact_staff')

travel/staff/views/landmark.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, DeleteView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from question.decorators import staff_required
# from trip.models import Landmark


# @method_decorator([login_required, staff_required], name='dispatch')
# class LandmarkCreateView(CreateView):
#     model = Landmark
#     context_object_name = 'landmark'
#     template_name = 'staff/landmark/landmark_create.html'
#     fields = ['name', ]
#     def get_success_url(self):
#         return reverse_lazy('other_staff')


# @method_decorator([login_required, staff_required], name='dispatch')
# class LandmarkUpdateView(UpdateView):
#     model = Landmark
#     context_object_name = 'landmark'
#     template_name = 'staff/landmark/landmark_update.html'
#     fields = ['name', ]
#     def get_success_url(self):
#         return reverse_lazy('other_staff')


# @method_decorator([login_required, staff_required], name='dispatch')
# class LandmarkDeleteView(DeleteView):
#     model = Landmark
#     context_object_name = 'landmark'
#     template_name = 'staff/landmark/landmark_delete.html'
#     def get_success_url(self):
#         return reverse_lazy('other_staff')

travel/staff/templates/staff/location/location_create.html
{% extends 'base_admin.html' %}

{% load i18n %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block title %} Location Create {% endblock title %}

{% block content %}
<div class="container-fluid">
	<div class="card-body">
		<div class="card">
			<div class="card-header">
				<h5 class="card-title">{% trans "Create Location" %}</h5>
			</div>

			<div class="card-body">
				<form class="create-form" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form|crispy }}
					
					<!-- <input id="tags" name="tags" class="form-control" type="text" value="Sydney,Beijing" data-role="tagsinput" /> -->

					<!-- Submit btn -->
					<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">{% trans "Create" %}</button>
				</form>
			</div>

		</div>
	</div>
</div>
{% endblock content %}


{% block custom_css %}
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />-->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap.tagsinput/0.4.2/bootstrap-tagsinput.css" />
{% endblock %}

{% block custom_js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/bootstrap.tagsinput/0.4.2/bootstrap-tagsinput.min.js"></script>
{% endblock %}

travel/staff/templates/staff/location/location_delete.html
{% extends 'base_admin.html' %}
{% load i18n %}
{% block title %} Location Delete {% endblock title %}
{% block content %}
<div class="container-fluid">
    <div class="card-body">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">{% trans "Delete Location" %} #{{ location.id }}</h5>
            </div>

            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="alert alert-warning" role="alert">
                        {% trans "Are you sure you want to delete" %} <strong>{{ location }}</strong> ?
                    </div>
                    <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- https://getbootstrap.com/docs/4.0/components/modal/ -->

{% endblock content %}

travel/staff/templates/staff/location/location_image.html
{% extends 'base_admin.html' %}

{% load i18n %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block title %} Location Image {% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="card-body">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">{% trans "Location Image" %}</h5>
            </div>

            <div class="card-body">
                <form class="create-form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {{ form|crispy }}
                    <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

travel/staff/templates/staff/location/location_update.html
{% extends 'base_admin.html' %}

{% load i18n %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block title %} Location Update {% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="card-body">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">{% trans "Location Update" %} #{{ location.id }}</h5>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
					{{ form|crispy }}

                    <!-- {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}

                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}
                        {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% endfor %} -->

                    <button type="submit" class="btn btn-success">{% trans "Update" %}</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block custom_css %}
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />-->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap.tagsinput/0.4.2/bootstrap-tagsinput.css" />
{% endblock %}

{% block custom_js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/bootstrap.tagsinput/0.4.2/bootstrap-tagsinput.min.js"></script>
{% endblock %}

travel/staff/templates/staff/location/location_view.html
{% extends 'base_admin.html' %}

{% load i18n %}
{% load static %}

{% block title %} {% trans "Location Staff" %} {% endblock title %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800"><a href="https://datatables.net">{% trans "Location" %}</a></h1>
  <p class="mb-4"><a target="_blank" href="{% url 'location_admin:location_create' %}">{% trans "Create Location" %}</a>.</p>

  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">{% trans "Location" %}</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>{% trans "Location Name" %}</th>
              <th>{% trans "Category" %}</th>
              <th>{% trans "Cost" %}</th>
              <th>{% trans "Time" %}</th>
              <th>{% trans "Image" %}</th>
              <th>{% trans "Update" %}</th>
              <th>{% trans "Delete" %}</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>{% trans "Location Name" %}</th>
              <th>{% trans "Category" %}</th>
              <th>{% trans "Cost" %}</th>
              <th>{% trans "Time" %}</th>
              <th>{% trans "Image" %}</th>
              <th>{% trans "Update" %}</th>
              <th>{% trans "Delete" %}</th>
            </tr>
          </tfoot>
          <tbody>
            {% for item in locations %}
            <tr>
              <td><a href="{% url 'location_admin:location_detail' item.pk %}">{{ item.name }}</a></td>
              <td>{{ item.category_sub }}</td>
              <td>{{ item.cost }} {% trans "BTH" %}</td>
              <td>{{ item.time_open }} - {{ item.time_close }}</td>
              <td><a href="{% url 'location_admin:location_image' %}">{% trans "Add Image" %}</a></td>
              <td><a href="{% url 'location_admin:location_update' item.pk %}">{% trans "Update" %}</a></td>
              <td><a href="{% url 'location_admin:location_delete' item.pk %}">{% trans "Delete" %}</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>
<!-- /.container-fluid -->
{% endblock content %}

{% block custom_css %}
<!-- Custom styles for this page -->
<link href="{% static 'admin/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block custom_js %}
<!-- Page level plugins -->
<script src="{% static 'admin/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'admin/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<!-- Page level custom scripts -->
<script src="{% static 'admin/js/demo/datatables-demo.js' %}"></script>
{% endblock %}