travel/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api.views import changeLanguage
from api.views import CategoryMainViewSet, CategorySubViewSet, LocationViewSet, LocationGalleryViewSet, TripViewSet, StyleViewSet

router = DefaultRouter()

router.register('api_category_main', CategoryMainViewSet)
router.register('api_category_sub', CategorySubViewSet)
router.register('api_location', LocationViewSet)
router.register('api_location_gallery', LocationGalleryViewSet)

router.register('api_trip', TripViewSet)
router.register('api_trip_style', StyleViewSet)


app_name = 'api'

urlpatterns = [
    path('', include(router.urls), name="api_location"),
    path('change/<slug:language>', changeLanguage, name="change-language"),

]

travel/location/urls.py
from django.urls import include, path
from . import views

app_name = 'location'

urlpatterns = [
    path('search/', views.search, name='search'),

    # path('', views.LocationListView.as_view(), name='location_list'),
    path('', views.location_list, name='location_list'),
    path('detail/<int:pk>/', views.LocationDetail, name='location_detail'),
]

travel/travel/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from general.views import home_view

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
	must_authenticate_view,
)

from question.views import question, active
from staff.views import staff 




urlpatterns = [

    path('api/', include('api.urls')),

    path('login/', login_view, name="login"),
    # path('logout/', logout_view, name="logout"),
	path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),


    path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/signup/', question.SignUpView.as_view(), name='signup'),
    path('accounts/signup/active/', active.ActiveSignUpView.as_view(), name='active_signup'),
    path('accounts/signup/staff/', staff.StaffSignUpView.as_view(), name='staff_signup'),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    
] 
urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),


    path('', home_view, name="home"),
    path('', include('api.urls')),
    path('blog/', include('blog.urls', 'blog')),
    path('trip/', include('trip.urls'), name='trip'),
    path('location/', include('location.urls'), name='location'),
    path('question/', include('question.urls')),
    path('contact/', include('general.urls')),
    path('hotel/', include('hotel.urls'), name="hotel"),
    path('account/', account_view, name="account"),
    path('staff/', include('staff.urls'), name="staff"),

)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travel/trip/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

from trip import views

app_name = 'trip'

urlpatterns = [
    

	path('trip_location/', views.trip_location, name="trip_location"),
	path('trip_summary/', views.trip_summary, name="trip_summary"),
	path('update_item/', views.updateItem, name="update_item"),
	path('trip_process/', views.trip_process, name="process_order"),


	path('my_trip/', views.myTrip, name="my_trip"),


    # path('person/', views.PersonCreate, name='trip_person_create'),
    # path('person/save', views.person_save, name='person_save'),
    # path('ajax/load-locations/', views.load_locations, name='ajax_load_locations'),
   
    path('system/', views.system_create, name='trip_system_create'),
    path('system/save/', views.trip_system_save, name='trip_system_save'),


    path('', views.trip_view, name='trip_list'),
    path('search/', views.search, name='search'),
    path('detail/<str:token>/', views.trip_detail, name='trip_detail'),
    path('tag/<slug:slug>/', views.tagged, name="tagged"),
    path('load-map/<str:token>/', views.load_map, name='load_map'),
]

travel/trip/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
# from django.utils.translation import gettext as _ 
from location.models import CategoryMain, CategorySub, Location
from account.models import Account

# CHOICES
class TypeAdventure(models.TextChoices):
    HARD = 'Hard Adventure', _('Hard Adventure')
    SOFT = 'Soft Adventure', _('Soft Adventure')
    NON = 'Non Adventure', _('Non Adventure')

class TypeSeason(models.TextChoices):
    WINTER = 'Winter', _('Winter')
    RAINY = 'Rainy', _('Rainy')
    SUMMER = 'Summer', _('Summer'),
    Every = 'Every Season', _('Every Seasons')

class SuitablePerson(models.TextChoices):
    CHILD = 'Child', _('Child')
    TEEN = 'Teen', _('Teen')
    ADULT = 'Adult', _('Adult'),
    ELDER = 'Elder', _('Elder'),
    Every = 'Everyone', _('Everyone')

class TypeGenerate(models.TextChoices):
    USER = 'User', _('User'),
    SYSTEM = 'System', _('System'),


class Style(models.Model):
    th_name = models.CharField(max_length=100)
    en_name = models.CharField(max_length=100, null=True, blank=True)
    
    def __str__(self):
        return self.th_name


class Trip(models.Model):

    customer        = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered    = models.DateTimeField(auto_now_add=True)
    complete        = models.BooleanField(default=False)
    # transaction_id  = models.CharField(max_length=100, null=True, unique=True)

    name 				    = models.CharField(null=True, max_length=50, unique=True, help_text='ตัวอย่าง: ทริปธรรมชาติและการถ่ายรูป')
    budget                  = models.IntegerField(default=0, null=True, blank=True)
    time_start              = models.TimeField(default=timezone.now)
    time_hotel              = models.TimeField(default=timezone.now)
    token                   = models.CharField(max_length=50, blank=True)
    location_start          = models.CharField(max_length=50, blank=True)
    person_number           = models.IntegerField(default=0, null=True, blank=True)
    style                   = models.ForeignKey(Style, on_delete=models.SET_NULL, null=True)
    category_sub            = models.ManyToManyField(CategorySub, null=True)
    tags 					= TaggableManager(help_text='เพิ่ม tag แหล่งท่องเที่ยวโดยพิมพ์ tag แล้วกด Enter')
    type_adventure          = models.CharField(null=True, blank=True, max_length=30, choices=TypeAdventure.choices)
    type_season             = models.CharField(null=True, blank=True, max_length=30, choices=TypeSeason.choices)
    suitable_person         = models.CharField(null=True, blank=True, max_length=30, choices=SuitablePerson.choices)
    trip_description_json   = models.TextField(null=True, blank=True)
    trip_description_text   = models.TextField(null=True, blank=True)


    def __str__(self):
        return str(self.name)
    
    @property
    def get_cost_total(self):
        triplocations = self.triplocation_set.all()
        total = sum([item.get_cost for item in triplocations])
        return total 
        
    @property
    def get_time_items(self):
        triplocations = self.triplocation_set.all()
        total = sum([item.time for item in triplocations])
        return total

    class Meta:
        verbose_name = "Trip"
        verbose_name_plural = "Trips"



class TripLocation(models.Model):
	location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Trip, on_delete=models.SET_NULL, null=True)
	time = models.IntegerField(default=0, null=True, blank=True)
	date_added = models.DateTimeField(auto_now_add=True)

	@property
	def get_cost(self):
		return self.location.cost

travel/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from account.models import Account


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

    class Meta:
        model = Account
        fields = ('email', 'username', 'password1', 'password2', )


class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")


class AccountUpdateForm(forms.ModelForm):

	class Meta:
		model = Account
		fields = ('email', 'username', )

	def clean_email(self):
		email = self.cleaned_data['email']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Account.DoesNotExist:
			return email
		raise forms.ValidationError('Email "%s" is already in use.' % account)

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except Account.DoesNotExist:
			return username
		raise forms.ValidationError('Username "%s" is already in use.' % username)

travel/trip/templates/trip/trip_person/my_trips.html
{% extends 'base_1.html' %}
{% load i18n %}
{% load static %}
{% block content %}
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <section id="breadcrumbs" class="breadcrumbs">
    <div class="breadcrumb-hero">
      <div class="container">
        <div class="breadcrumb-hero">
          <h2>{% trans "My Trip" %}</h2>
        </div>
      </div>
    </div>
    <div class="container">
      <ol>
        <li><a href="{% url 'home' %}">{% trans "Home" %}</a></li>
        <li>{% trans "My Trip" %}</li>
      </ol>
    </div>
  </section>
  <!-- End Breadcrumbs -->


  <!-- ======= Blog Section ======= -->
  <section id="blog" class="blog">
    <div class="container">
      <div class="row">
        <!-- Loads all of the Current users reservations in a list and displays all  the details -->
        {% for trip in trips %}
        {% include 'trip/trip_person/snippets/my_trip_snippet.html'%}
        {% endfor %}
      </div>
    </div>
  </section><!-- End Blog Section -->

</main>
{% endblock %}

travel/trip/templates/trip/trip_person/trip_location.html
{% extends 'base_1.html' %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="row" style="padding-top: 5em;">
	<div class="col-lg-12">
		<div class="box-element ml-4 mr-4">
			<div class="text-center">
			<a class="btn btn-outline-success" href="{% url 'location:location_list' %}" style="float: left;">&#x2190; {% trans "Choose Location" %}</a>
			<h5 style="padding-top: 5px;">{% trans "Choose attractions in your trip" %}</h5>			
			</div>
			<br>
			<br>
			<table class="table">
				<tr>
					<th>
						<h5>{% trans "Time" %}: <strong>{{ order.get_time_items }} {% trans "minute" %}</strong></h5>
					</th>
					<th>
						<h5>{% trans "Total" %}: <strong>{{ order.get_cost_total|floatformat:2 }} {% trans "BTH" %}</strong></h5>
					</th>
					<th>
						<a style="float:right; margin:5px;" class="btn btn-success"
							href="{% url 'trip:trip_summary' %}">{% trans "Summary" %}</a>
						<!-- <a style="float:right; margin:5px;" class="btn btn-outline-success" href="{% url 'trip:trip_summary' %}">{% trans "Summary" %} &#x2192; </a> -->
					</th>
				</tr>
			</table>

		</div>

		<br>
		<div class="box-element">
			<div class="cart-row">
				<div style="flex:1"></div>
				<div style="flex:2"><strong>{% trans "Place Name" %}</strong></div>
				<div style="flex:1"><strong>{% trans "Cost" %}</strong></div>
				<div style="flex:1"><strong>{% trans "Time" %}({% trans "minute" %})</strong></div>
				<div style="flex:1"><strong>{% trans "Delete" %}</strong></div>
			</div>
			{% if items %}
			{% for item in items %}
			<div class="cart-row">
				<div style="flex:1"><img class="row-image" src="{{ item.location.image.all.0.image.url }}"></div>
				<div style="flex:2">
					<p>{{ item.location.name }}</p>
				</div>
				<div style="flex:1">
					<p>{{ item.location.cost|floatformat:2 }} {% trans "BTH" %}</p>
				</div>
				<div style="flex:1">
					<p class="quantity">{{ item.time }}</p>
					<div class="quantity">
						<img data-location="{{ item.location.id }}" data-action="add" class="chg-time update-cart"
							src="{% static  'images/arrow-up.png' %}">
						<img data-location="{{ item.location.id }}" data-action="remove"
							class="chg-time update-cart" src="{% static  'images/arrow-down.png' %}">
					</div>
				</div>
				<div style="flex:1">
					<img data-location="{{ item.location.id }}" data-action="clear" class="icon-remove update-cart"  src="{% static  'images/trash.png' %}">
				</div>
			</div>
			{% endfor %}
			{% else %}
			<div class="text-center" >
				<p>{% trans "No Location" %}</p>
			</div>
			{% endif %}
		</div>
	</div>
</div>
{% endblock content %}

{% block custom_js %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
{% endblock %}

travel/trip/templates/trip/trip_person/trip_summary.html
{% extends 'base_1.html' %}
{% load i18n %}
{% load static %}
{% load mathfilters %}
{% block content %}
<div class="row" style="padding-top: 5em; padding-bottom: 5em;">
	<div class="col-lg-6">
		<div class="box-element" id="form-wrapper">
			<form id="form">
				{%csrf_token%}
				<div class="form-row mt-4">
					<div class="col">
						<label>{% trans "Trip Name" %}</label>
						<input class="multisteps-form__input form-control" type="text" name="name" required id="id_name"
							placeholder="{% trans 'Examples: nature trips' %}" />
					</div>
					<div class="col">
						<label>{% trans "Person Number" %}</label>
						<input class="multisteps-form__input form-control" type="number" name="person_number" value="1"
							min="1" required placeholder="{% trans 'Person Number' %}" />
					</div>
				</div>

				{% if not request.user.is_authenticated %}
				<div class="form-row mt-4">
					<div class="col">
						<label>{% trans "Email" %}</label>
						<input class="multisteps-form__input form-control" type="email" name="email" required
							id="id_email" placeholder="{% trans 'Email' %}" />
					</div>
				</div>
				{% endif %}

				<div class="form-row mt-4">
					<div class="col">
						<label>{% trans "Location Start" %}</label>
						<select name="province" class="pick-animation__select form-control">
							<!-- <option value="">---------</option> -->
							{% for province in provinces %}
							<option value="{{ province }}">
								<datagrid>{{ province }}</datagrid>
							</option>
							{% endfor %}
						</select>
					</div>
					<div class="col">
						<label>{% trans "Tourism style" %}</label>
						<select name="styles" class="pick-animation__select form-control">
							<!-- <option value="">---------</option> -->
							{% for style in styles %}
							{% if LANGUAGE_CODE == 'en' %}
							<option value="{{ style.id }}">{{ style.en_name }}</option>
							{% else %}
							<option value="{{ style.id }}">{{ style.th_name }}</option>
							{% endif %}
							{% endfor %}
						</select>
					</div>
				</div>

				<div class="form-row mt-4">
					<div class="col">
						<label>{% trans "Type Adventure" %}</label>
						<select name="type_adventure" class="pick-animation__select form-control">
							<!-- <option value="">---------</option> -->
							{% for item in TypeAdventure %}
							<option value="{{ item }}">
								<datagrid>{{ item.label }}</datagrid>
							</option>
							{% endfor %}
						</select>
					</div>
					<div class="col">
						<label>{% trans "Suitable For The Season" %}</label>
						<select name="type_season" class="pick-animation__select form-control">
							<!-- <option value="">---------</option> -->
							{% for item in TypeSeason %}
							<option value="{{ item }}">{{ item.label }}</option>
							{% endfor %}
						</select>
					</div>
					<div class="col">
						<label>{% trans "Suitable Person" %}</label>
						<select name="suitable_person" class="pick-animation__select form-control">
							<!-- <option value="">---------</option> -->
							{% for item in SuitablePerson %}
							<option value="{{ item }}">{{ item.label }}</option>
							{% endfor %}
						</select>
					</div>
				</div>

				<div class="form-row mt-4">
					<div class="col">
						<label>{% trans "Time to start traveling" %}</label>
						<input class="multisteps-form__input form-control" type="text" name="time_start" id="time_start"
							pattern="[0-2][0-9]:[0-6][0-9]:[0-6][0-9]"
							placeholder="{% trans 'Example 09:00:00 (hour: minute: second)' %}" required />
					</div>
					<div class="col">
						<label>{% trans "Time of entering the accommodation" %}</label>
						<input class="multisteps-form__input form-control" type="text" name="time_hotel" id="time_hotel"
							pattern="[0-2][0-9]:[0-6][0-9]:[0-6][0-9]"
							placeholder="{% trans 'Example 09:00:00 (hour: minute: second)' %}" required />
					</div>
				</div>


				<div class="form-row mt-4">
					<div class="col">
						<label>{% trans "More Details" %}</label>
						<textarea class="multisteps-form__textarea form-control" name="description"
							placeholder="{% trans 'More Details' %}"></textarea>
					</div>
				</div>

				<hr>
				<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
			</form>
		</div>

		<br>
		<div class="text-center hidden" id="confirm-info">
			<small>{% trans "You cannot edit the trip" %}</small>
			<button class="btn btn-warning" id="make-confirm">{% trans "Confirm" %}</button>
		</div>

	</div>

	<div class="col-lg-6">
		<div class="box-element">
			<a class="btn btn-outline-success" href="{% url 'trip:trip_location' %}">&#x2190;
				{% trans "Back To Location List" %}</a>
			<hr>
			<h3>{% trans "Location Trip Summary" %}</h3>
			<hr>
			{% for item in items %}
			<div class="cart-row">
				<div style="flex:2"><img class="row-image" src="{{ item.location.image.all.0.image.url }}"></div>
				<div style="flex:2">
					<p>{{ item.location.name }}</p>
				</div>
				<div style="flex:1">
					<p>{{ item.location.cost|floatformat:2 }} {% trans "BTH" %}</p>
				</div>
				<div style="flex:1">
					<p>{{ item.time }} {% trans "minute" %}</p>
				</div>
			</div>
			{% endfor %}
			<h5>{% trans "Time" %}: {{ order.get_time_items }} {% trans "minute" %} {% trans "or" %} {{ order.get_time_items|div:60 }} {% trans "hours" %}</h5>
			<h5>{% trans "Total" %}: {{ order.get_cost_total|floatformat:2 }} {% trans "BTH" %}</h5>
		</div>
	</div>
</div>
{% endblock content %}


{% block custom_css %}
<link rel="stylesheet" href="{% static 'css/bootstrap-material-datetimepicker.css' %}" />
{% endblock %}

{% block custom_js %}

<script src="https://code.jquery.com/jquery-1.12.3.min.js"
	integrity="sha256-aaODHAgvwQW1bFOGXMeX+pC4PZIPsvn2h1sArYOhgXQ=" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.5.10/js/ripples.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.5.10/js/material.min.js"></script>
<script type="text/javascript"
	src="https://rawgit.com/FezVrasta/bootstrap-material-design/master/dist/js/material.min.js"></script>
<script type="text/javascript" src="http://momentjs.com/downloads/moment-with-locales.min.js"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-material-datetimepicker.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<script type="text/javascript">
	$('#time_start').bootstrapMaterialDatePicker
		({
			date: false,
			shortTime: false,
			format: 'HH:mm:ss'
		});
	$('#time_hotel').bootstrapMaterialDatePicker
		({
			date: false,
			shortTime: false,
			format: 'HH:mm:ss'
		});

	// Swal.fire({
	// 	title: 'Are you sure?',
	// 	text: "You won't be able to revert this!",
	// 	icon: 'warning',
	// 	showCancelButton: true,
	// 	confirmButtonColor: '#3085d6',
	// 	cancelButtonColor: '#d33',
	// 	confirmButtonText: 'Yes, delete it!'
	// }).then((result) => {
	// 	if (result.value) {
	// 		Swal.fire(
	// 			'Deleted!',
	// 			'Your file has been deleted.',
	// 			'success'
	// 		)
	// 	}
	// })

	var total = '{{ order.get_cost_total|floatformat:2 }}'

	var form = document.getElementById('form')
	form.addEventListener('submit', function (e) {
		e.preventDefault()
		console.log('Form Submitted...')
		document.getElementById('form-button').classList.add("hidden");
		document.getElementById('confirm-info').classList.remove("hidden");
	})

	document.getElementById('make-confirm').addEventListener('click', function (event) {
		event.preventDefault()
		submitFormData()
	})

	function submitFormData() {
		console.log('Payment button clicked')

		var userFormData = {
			'name': null,
			'email': null,
			'total': total,
		}

		var tripInfo = {
			'name': null,
			'person_number': null,
			'location_srart': null,
			'trip_styles': null,
			'time_start': null,
			'time_hotel': null,
			'trip_description': null,
			'type_adventure': null,
			'type_season': null,
			'suitable_person': null,
		}

		tripInfo.name = form.name.value
		tripInfo.person_number = form.person_number.value
		tripInfo.location_srart = form.province.value
		tripInfo.trip_styles = form.styles.value

		tripInfo.time_start = form.time_start.value
		tripInfo.time_hotel = form.time_hotel.value
		tripInfo.trip_description = form.description.value

		tripInfo.type_adventure = form.type_adventure.value
		tripInfo.type_season = form.type_season.value
		tripInfo.suitable_person = form.suitable_person.value

		if (user == 'AnonymousUser') {
			userFormData.name = form.name.value
			userFormData.email = form.email.value
		}

		console.log('Trip Info:', tripInfo)
		console.log('User Info:', userFormData)

		var url = "{% url 'trip:process_order' %}"
		// var url = "/trip/process_order/"

		fetch(url, {
			method: 'POST',
			headers: {
				'Content-Type': 'applicaiton/json',
				'X-CSRFToken': csrftoken,
			},
			body: JSON.stringify({ 'form': userFormData, 'trip': tripInfo }),

		})
			.then((response) => response.json())
			.then((data) => {
				console.log('Success:', data);
				// alert('Trip completed');
				Swal.fire({
					icon: 'success',
					title: 'Your trip has been saved',
					showConfirmButton: false,
					timer: 1500
				}).then((result) => {
					// Generate URL without "id" bit
					var trip_detail = "{% url 'trip:trip_list' %}";
					// var token = $(this).attr(data);
					var token = data;
					var url = trip_detail + "detail" + "/" + token;

					cart = {}
					document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
					// Construct the full URL with "id"
					window.location.href = url;
				})
			})
	}
</script>
{% endblock %}