travel/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api.views import changeLanguage
from api.views import CategoryMainViewSet, CategorySubViewSet, LocationViewSet, LocationGalleryViewSet, TripViewSet, StyleViewSet

router = DefaultRouter()

router.register('api_category_main', CategoryMainViewSet)
router.register('api_category_sub', CategorySubViewSet)
router.register('api_location', LocationViewSet)
router.register('api_location_gallery', LocationGalleryViewSet)

router.register('api_trip', TripViewSet)
router.register('api_trip_style', StyleViewSet)


app_name = 'api'

urlpatterns = [
    path('', include(router.urls), name="api_location"),
    path('change/<slug:language>', changeLanguage, name="change-language"),

]

travel/question/urls.py
from django.urls import include, path

from question.views import question, active

urlpatterns = [

    path('active/', include(([
        path('', active.QuizListView.as_view(), name='quiz_list'),
        path('interests/', active.ActiveInterestsView.as_view(), name='active_interests'),
        path('taken/', active.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', active.take_quiz, name='take_quiz'),
    ], 'question'), namespace='active')),

]

travel/staff/urls.py
from django.urls import include, path
# from hotel.views import 
# from ManageHotels.views import ChartData,ChartView

from staff.views import (
    staff, location, category, question, season, other, style, landmark, contact, hotel,
    partner,
    )

# app_name = 'staff'

urlpatterns = [

    path('', staff.home_view, name='home_admin'),

    path('location/', include(([
        path('', location.location_view, name='location_view'),
        path('image/', location.LocationGalleryCreateView.as_view(), name='location_image'),
        path('create/', location.location_create_view, name='location_create'),
        path('detail/<int:pk>/', location.LocationDetail, name='location_detail'),
        # path('update/<int:pk>/', location.location_update_view, name='location_update'),
        path('update/<int:pk>/', location.LocationUpdateView.as_view(), name='location_update'),
        path('delete/<int:pk>/', location.LocationDeleteView.as_view(), name='location_delete'),
    ], 'staff'), namespace='location_admin')),    


    path('category/', include(([
        path('', category.CategoryListView.as_view(), name='category_view'),
        path('create/', category.CategoryCreateView.as_view(), name='category_create'),
        path('update/<int:pk>/', category.CategoryUpdateView.as_view(), name='category_update'),
        path('delete/<int:pk>', category.CategoryDeleteView.as_view(), name='category_delete'),
    ], 'staff'), namespace='category_admin')),    


    path('question/', include(([
        path('', question.QuizListView.as_view(), name='quiz_change_list'),
        path('quiz/add/', question.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/results/view', question.results_view, name='results_view'),
        path('quiz/<int:pk>/', question.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', question.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', question.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', question.question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', question.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', question.QuestionDeleteView.as_view(), name='question_delete'),
        path('generate/', question.generate_report, name='generate_report'),
    ], 'staff'), namespace='question_admin')),

    # path('other/', other.other_staff, name='other_staff'),
    path('contact/', other.contact_staff, name='contact_staff'),


    # path('season/', include(([
    #     path('create/', season.SeasonCreateView.as_view(), name='season_create'),
    #     path('update/<int:pk>/', season.SeasonUpdateView.as_view(), name='season_update'),
    #     path('delete/<int:pk>/', season.SeasonDeleteView.as_view(), name='season_delete'),
    # ], 'staff'), namespace='season_admin')),

    # path('style/', include(([
    #     path('create/', style.StyleCreateView.as_view(), name='style_create'),
    #     path('update/<int:pk>/', style.StyleUpdateView.as_view(), name='style_update'),
    #     path('delete/<int:pk>/', style.StyleDeleteView.as_view(), name='style_delete'),
    # ], 'staff'), namespace='style_admin')),


    # path('landmark/', include(([
    #     path('create/', landmark.LandmarkCreateView.as_view(), name='landmark_create'),
    #     path('update/<int:pk>/', landmark.LandmarkUpdateView.as_view(), name='landmark_update'),
    #     path('delete/<int:pk>/', landmark.LandmarkDeleteView.as_view(), name='landmark_delete'),
    # ], 'staff'), namespace='landmark_admin')),


    path('contact/', include(([
        path('create/', contact.ContactCreateView.as_view(), name='contact_create'),
        path('update/<int:pk>/', contact.ContactUpdateView.as_view(), name='contact_update'),
        path('delete/<int:pk>/', contact.ContactDeleteView.as_view(), name='contact_delete'),
    ], 'staff'), namespace='contact_admin')),


     path('hotel/', include(([
     # path('', views.showhotels, name='showhotel'),
        path('', hotel.home, name='home'),

        path('hotel', hotel.showhotels, name='hotel_view'),
        path('hotel/create', hotel.HotelCreateView.as_view(), name='hotel_create'),
        path('hotel/update/(<pk>[0-9]+)', hotel.HotelUpdateView.as_view(), name='hotel_update'),
        path('hotel/delete/(<pk>[0-9]+)', hotel.HotelDeleteView.as_view(), name='hotel_delete'),

          # Bookings
        path('hotel/bookings/(<pk>[0-9]+)', hotel.showreservations, name='hotel_reservations'),
        path('hotel/bookings/delete/(<pk>[0-9]+)', hotel.cancelbooking, name='booking_remove'),
          
          
          # Room
        path('hotel/room/(<pk>[0-9]+)', hotel.managehotel, name='room_view'),
        path('hotel/rooms/create/(<pk>[0-9]+)', hotel.RoomCreateView.as_view(), name='room_create'),
        path('hotel/rooms/update/(<pk>[0-9]+)', hotel.RoomUpdateView.as_view(), name='room_update'),
        path('hotel/rooms/delete/(<pk>[0-9]+)', hotel.RoomDeleteView.as_view(), name='room_delete'),
          
          # Photo
        path('hotel/photo/(<id>[0-9]+)', hotel.showphotodash, name='photo_view'),
        path('hotel/photo/upload(<id>[0-9]+)', hotel.BasicUploadView.as_view(), name='photo_upload'),
        path('hotel/photo/delete/(<id>[0-9]+)', hotel.deletePhoto, name='photo_delete'),
        path('hotel/photo/thumbnail(<id>[0-9]+)', hotel.editThumbnail, name='editThumb'),

          # Chart
        path('charts/(<id>[0-9]+)/', hotel.ChartView.as_view(), name = 'partner_charts'),
        path('chart/data/(<id>[0-9]+)/', hotel.ChartData.as_view()),


        path('zxc', partner.displayDash, name='displayDash'),

        path('partners', partner.showPartners, name='showpartners'),
        path('partners/remove/(<id>[0-9]+)', partner.removePartner, name='removepartner'),

        path('proposals', partner.showProposals, name='showproposals'),
        path('proposals/accept/(<id>[0-9]+)', partner.acceptProposals, name='acceptproposal'),
        path('proposals/decline/(<id>[0-9]+)', partner.declineProposals, name='declineproposal'),
        
        path('partner/checkstatus', partner.checkstatus, name='proposal_check'),
    
     ], 'staff'), namespace='hotel_admin')),

]

travel/travel/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from general.views import home_view

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
	must_authenticate_view,
)

from question.views import question, active
from staff.views import staff 




urlpatterns = [

    path('api/', include('api.urls')),

    path('login/', login_view, name="login"),
    # path('logout/', logout_view, name="logout"),
	path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),


    path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/signup/', question.SignUpView.as_view(), name='signup'),
    path('accounts/signup/active/', active.ActiveSignUpView.as_view(), name='active_signup'),
    path('accounts/signup/staff/', staff.StaffSignUpView.as_view(), name='staff_signup'),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    
] 
urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),


    path('', home_view, name="home"),
    path('', include('api.urls')),
    path('blog/', include('blog.urls', 'blog')),
    path('trip/', include('trip.urls'), name='trip'),
    path('location/', include('location.urls'), name='location'),
    path('question/', include('question.urls')),
    path('contact/', include('general.urls')),
    path('hotel/', include('hotel.urls'), name="hotel"),
    path('account/', account_view, name="account"),
    path('staff/', include('staff.urls'), name="staff"),

)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travel/question/models.py
from django.db import models
from django.utils.html import escape, mark_safe
from account.models import Account
# from location.models import CategoryMain

class Subject(models.Model):
    name        = models.CharField(max_length=30)
    color       = models.CharField(max_length=7, default='#007bff')

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (color, name)
        return mark_safe(html)


class Quiz(models.Model):
    owner       = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='quizzes')
    name        = models.CharField(max_length=255)
    subject     = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='quizzes')

    def __str__(self):
        return self.name


class Question(models.Model):
    quiz        = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    text        = models.CharField('Question', max_length=255)

    def __str__(self):
        return self.text


class Answer(models.Model):
    question        = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text            = models.CharField('Answer', max_length=255)
    is_correct      = models.BooleanField('Correct answer', default=False)

    def __str__(self):
        return self.text


class Active(models.Model):
    user        = models.OneToOneField(Account, on_delete=models.CASCADE, primary_key=True)
    # quizzes     = models.ManyToManyField(Quiz)
    quizzes   = models.ManyToManyField(Quiz, through='TakenQuiz')
    interests   = models.ManyToManyField(Subject, related_name='interested_user')

    def get_unanswered_questions(self, quiz):
        answered_questions = self.quiz_answers \
            .filter(answer__question__quiz=quiz) \
            .values_list('answer__question__pk', flat=True)
        questions = quiz.questions.exclude(pk__in=answered_questions).order_by('text')
        return questions

    def __str__(self):
        return self.user.username
        


class TakenQuiz(models.Model):
    active      = models.ForeignKey(Active, on_delete=models.CASCADE, related_name='taken_quizzes')
    quiz        = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='taken_quizzes')
    score       = models.FloatField()
    date        = models.DateTimeField(auto_now_add=True)


class ActiveAnswer(models.Model):
    active      = models.ForeignKey(Active, on_delete=models.CASCADE, related_name='quiz_answers')
    answer      = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='+')
    

travel/staff/models.py
from django.db import models

# Create your models here.

travel/staff/forms.py
from django import forms
from hotel.models import Photo

# Using djangos Model forms to create a form using a model.


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['path', ]

travel/question/views/question.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            return redirect('staff:quiz_change_list')
        else:
            return redirect('active:quiz_list')
    return redirect('home')
    # return render(request, 'question/home.html')

travel/staff/views/category.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, DeleteView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from question.decorators import staff_required
from location.models import CategorySub


@method_decorator([login_required, staff_required], name='dispatch')
class CategoryListView(ListView):
    model = CategorySub
    context_object_name = 'categorys'
    template_name = 'staff/category/category_view.html'

    
@method_decorator([login_required, staff_required], name='dispatch')
class CategoryCreateView(CreateView):
    model = CategorySub
    context_object_name = 'category'
    template_name = 'staff/category/category_create.html'
    fields = ['name', 'category_main']

    def get_success_url(self):
        return reverse_lazy('category_admin:category_view')


@method_decorator([login_required, staff_required], name='dispatch')
class CategoryUpdateView(UpdateView):
    model = CategorySub
    context_object_name = 'category'
    template_name = 'staff/category/category_update.html'
    fields = ['name', 'category_main']

    def get_success_url(self):
        return reverse_lazy('category_admin:category_view')


@method_decorator([login_required, staff_required], name='dispatch')
class CategoryDeleteView(DeleteView):
    model = CategorySub
    context_object_name = 'category'
    template_name = 'staff/category/category_delete.html'
    success_url = reverse_lazy('category_admin:category_view')

travel/staff/views/contact.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, DeleteView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from question.decorators import staff_required
from general.models import Contact, ContactDetail


@method_decorator([login_required, staff_required], name='dispatch')
class ContactCreateView(CreateView):
    model = ContactDetail
    context_object_name = 'contact'
    template_name = 'staff/contact/contact_create.html'
    fields = ['name', 'contact', 'phone', 'email', 'address']
    def get_success_url(self):
        return reverse_lazy('contact_staff')


@method_decorator([login_required, staff_required], name='dispatch')
class ContactUpdateView(UpdateView):
    model = ContactDetail
    context_object_name = 'contact'
    template_name = 'staff/contact/contact_update.html'
    fields = ['name', 'contact', 'phone', 'email', 'address']
    def get_success_url(self):
        return reverse_lazy('contact_staff')


@method_decorator([login_required, staff_required], name='dispatch')
class ContactDeleteView(DeleteView):
    model = ContactDetail
    context_object_name = 'contact'
    template_name = 'staff/contact/contact_delete.html'
    def get_success_url(self):
        success_url = reverse_lazy('contact_staff')

travel/staff/templates/staff/question/question_add_form.html
{% extends 'base_admin.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid">
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800"><a href="{% url 'question_admin:quiz_change_list' %}">{% trans "My Quizzes" %}</a></h1>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'question_admin:quiz_change_list' %}">{% trans "My Quizzes" %}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'question_admin:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{% trans "Add a new question" %}</li>
    </ol>
  </nav>
  
  <h2 class="mb-3">{% trans "Add a new question" %}</h2>
  <p class="lead">{% trans "Add first the text of the question. In the next step you will be able to add the possible answers" %}.</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">{% trans "Save" %}</button>
    <a href="{% url 'question_admin:quiz_change' quiz.pk %}" class="btn btn-outline-secondary" role="button">{% trans "Nevermind" %}</a>
  </form>
</div>
{% endblock %}

travel/staff/templates/staff/question/question_change_form.html
{% extends 'base_admin.html' %}

{% load i18n %}
{% load crispy_forms_tags crispy_forms_filters %}

{% block content %}
<div class="container-fluid">
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800"><a href="{% url 'question_admin:quiz_change_list' %}">{% trans "My Quizzes" %}</a></h1>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'question_admin:quiz_change_list' %}">{% trans "My Quizzes" %}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'question_admin:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ question.text }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ question.txt }}</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form|crispy }}
    <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
      <div class="card-header">
        <div class="row">
          <div class="col-8">
            <strong>{% trans "Answers" %}</strong>
          </div>
          <div class="col-2">
            <strong>{% trans "Correct" %}?</strong>
          </div>
          <div class="col-2">
            <strong>{% trans "Delete" %}?</strong>
          </div>
        </div>
      </div>
      {% for error in formset.non_form_errors %}
        <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
      {% endfor %}
      <div class="list-group list-group-flush list-group-formset">
        {% for form in formset %}
          <div class="list-group-item">
            <div class="row">
              <div class="col-8">
                {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                {{ form.text|as_crispy_field }}
                {% if form.instance.pk and form.text.value != form.instance.text %}<p class="mb-0 mt-1"><small class="text-muted font-italic"><strong>Old answer:</strong> {{ form.instance.text }}</small></p>{% endif %}
              </div>
              <div class="col-2">
                {{ form.is_correct }}
              </div>
              <div class="col-2">
                {% if form.instance.pk %}
                  {{ form.DELETE }}
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <p>
      <small class="form-text text-muted">{% trans "our question may have at least" %} <strong>2</strong> {% trans "answers and maximum" %} <strong>10</strong> answers. Select at least one correct answer.</small>
    </p>
    <button type="submit" class="btn btn-success">{% trans "Save changes" %}</button>
    <a href="{% url 'question_admin:quiz_change' quiz.pk %}" class="btn btn-outline-secondary" role="button">{% trans "Nevermind" %}</a>
    <a href="{% url 'question_admin:question_delete' quiz.pk question.pk %}" class="btn btn-danger float-right">{% trans "Delete" %}</a>
  </form>
</div>
{% endblock %}

travel/staff/templates/staff/question/question_delete_confirm.html
{% extends 'base_admin.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container-fluid">
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800"><a href="https://datatables.net">{% trans "My Quizzes" %}</a></h1>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'question_admin:quiz_change_list' %}">{% trans "My Quizzes" %}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'question_admin:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'question_admin:question_change' quiz.pk question.pk %}">{{ question.text }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{% trans "Confirm deletion" %}</li>
    </ol>
  </nav>

  <h2 class="mb-3">{% trans "Confirm deletion" %}</h2>
  <p class="lead">{% trans "Are you sure you want to delete the question" %} <strong>"{{ question.text }}"</strong>? {% trans "There is no going back" %}.</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">{% trans "Yes, I'm sure" %}</button>
    <a href="{% url 'question_admin:question_change' quiz.pk question.pk %}" class="btn btn-outline-secondary btn-lg" role="button">{% trans "Nevermind" %}</a>
  </form>
</div>
{% endblock %}

travel/staff/templates/staff/question/quiz_change_form.html
{% extends 'base_admin.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid">
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800"><a href="https://datatables.net">{% trans "My Quizzes" %}</a></h1>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'question_admin:quiz_change_list' %}">{% trans "My Quizzes" %}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ quiz.name }}</li>
    </ol>
  </nav>
  
  <h2 class="mb-3">
    {{ quiz.name }}
    <a href="{% url 'question_admin:quiz_results' quiz.pk %}" class="btn btn-primary float-right">{% trans "View results" %}</a>
  </h2>
  <div class="row mb-3">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">{% trans "Save changes" %}</button>
        <a href="{% url 'question_admin:quiz_change_list' %}" class="btn btn-outline-secondary"
          role="button">{% trans "Nevermind" %}</a>
        <a href="{% url 'question_admin:quiz_delete' quiz.pk %}" class="btn btn-danger float-right">{% trans "Delete" %}</a>
      </form>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-10">
          <strong>{% trans "Questions" %}</strong>
        </div>
        <div class="col-2">
          <strong>{% trans "Answers" %}</strong>
        </div>
      </div>
    </div>
    <div class="list-group list-group-flush list-group-formset">
      {% for question in questions %}
      <div class="list-group-item">
        <div class="row">
          <div class="col-10">
            <a href="{% url 'question_admin:question_change' quiz.pk question.pk %}">{{ question.text }}</a>
          </div>
          <div class="col-2">
            {{ question.answers_count }}
          </div>
        </div>
      </div>
      {% empty %}
      <div class="list-group-item text-center">
        <p class="text-muted font-italic mb-0">{% trans "You haven't created any questions yet" %}. Go ahead and" %} <a
            href="{% url 'question_admin:question_add' quiz.pk %}">{% trans "add the first question" %}</a>.</p>
      </div>
      {% endfor %}
    </div>
    <div class="card-footer">
      <a href="{% url 'question_admin:question_add' quiz.pk %}" class="btn btn-primary btn-sm">{% trans "Add question" %}</a>
    </div>
  </div>
</div>
{% endblock %}

travel/staff/templates/staff/question/quiz_change_list.html
{% extends 'base_admin.html' %}

{% load i18n %}

{% block content %}
<div class="container-fluid">
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800"><a href="https://datatables.net">{% trans "My Quizzes" %}</a></h1>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">{% trans "My Quizzes" %}</li>
    </ol>
  </nav>

  <a href="{% url 'question_admin:quiz_add' %}" class="btn btn-primary mb-3" role="button">{% trans "Add quiz" %}</a>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>{% trans "Quiz" %}</th>
          <th>{% trans "Subject" %}</th>
          <th>{% trans "Questions" %}</th>
          <th>{% trans "Taken" %}</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
        <tr>
          <td class="align-middle"><a href="{% url 'question_admin:quiz_change' quiz.pk %}">{{ quiz.name }}</a></td>
          <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>
          <td class="align-middle">{{ quiz.questions_count }}</td>
          <td class="align-middle">{{ quiz.taken_count }}</td>
          <td class="text-right">
            <a href="{% url 'question_admin:quiz_results' quiz.pk %}" class="btn btn-primary">{% trans "View results" %}</a>
          </td>
        </tr>
        {% empty %}
        <tr>
          <td class="bg-light text-center font-italic" colspan="5">{% trans "You haven't created any quiz yet" %}.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}