travel/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api.views import changeLanguage
from api.views import CategoryMainViewSet, CategorySubViewSet, LocationViewSet, LocationGalleryViewSet, TripViewSet, StyleViewSet

router = DefaultRouter()

router.register('api_category_main', CategoryMainViewSet)
router.register('api_category_sub', CategorySubViewSet)
router.register('api_location', LocationViewSet)
router.register('api_location_gallery', LocationGalleryViewSet)

router.register('api_trip', TripViewSet)
router.register('api_trip_style', StyleViewSet)


app_name = 'api'

urlpatterns = [
    path('', include(router.urls), name="api_location"),
    path('change/<slug:language>', changeLanguage, name="change-language"),

]

travel/blog/urls.py
from django.urls import path
from blog.views import (
    home_screen_view,
	create_blog_view,
	detail_blog_view,
	edit_blog_view,
    tagged,
)

app_name = 'blog'

urlpatterns = [
    path('home/', home_screen_view, name="home" ),
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit/', edit_blog_view, name="edit"),
    path('<slug>/tag/', tagged, name="tagged"),

 ]

travel/hotel/urls.py
from django.conf.urls import url
from django.urls import include, path
from hotel.views import hotel, reservation

# app_name = 'hotel'

urlpatterns = [

     path('', hotel.hotelSearch.as_view(), name='home_hotel'),


     path('', include(([
          path('', hotel.hotelindex, name='hotel_view'),
          path('hotel/(<pk>[0-9]+)/', hotel.hoteldetails, name='hotel_detail'),
          path('hotel/search', hotel.hotelSearch.as_view(), name='hotel_search'),
          path('reviews/create/(<id>[0-9]+)', hotel.reviewCreateView.as_view(), name='review_create'),
          path('reviews/update/(<pk>[0-9]+)', hotel.reviewUpdateView.as_view(), name='review_update'),
          path('reviews/delete/(<pk>[0-9]+)', hotel.reviewDeleteView.as_view(), name='review_delete'),
          path('partner/apply', hotel.partnerCreateView.as_view(), name='proposal_create'),
    ], 'hotel'), namespace='hotel')),


     path('reservation/', include(([
          path('book/(<hotelid>[0-9]+)/(<roomid>[0-9]+)', reservation.bookRoom, name='bookroom'),
          path('book/create/(<roomid>[0-9]+)/(<hotelid>[0-9]+)/(<checkin>(\d{4}-\d{2}-\d{2}))/(<checkout>(\d{4}-\d{2}-\d{2}))/(<totalcost>[0-9]+)'
          , reservation.booking_create, name='booking_create'),

          path('mybookings/', reservation.mybookings, name='bookings_view'),
          path('mybookings/cancel/(<id>[0-9]+)', reservation.cancelbooking, name='booking_cancel'),
          path('mybookings/(<id>[0-9]+)/pdf', reservation.GeneratePDF.as_view(), name='gpdf'),
    ], 'hotel'), namespace='reservation')),

]

travel/staff/urls.py
from django.urls import include, path
# from hotel.views import 
# from ManageHotels.views import ChartData,ChartView

from staff.views import (
    staff, location, category, question, season, other, style, landmark, contact, hotel,
    partner,
    )

# app_name = 'staff'

urlpatterns = [

    path('', staff.home_view, name='home_admin'),

    path('location/', include(([
        path('', location.location_view, name='location_view'),
        path('image/', location.LocationGalleryCreateView.as_view(), name='location_image'),
        path('create/', location.location_create_view, name='location_create'),
        path('detail/<int:pk>/', location.LocationDetail, name='location_detail'),
        # path('update/<int:pk>/', location.location_update_view, name='location_update'),
        path('update/<int:pk>/', location.LocationUpdateView.as_view(), name='location_update'),
        path('delete/<int:pk>/', location.LocationDeleteView.as_view(), name='location_delete'),
    ], 'staff'), namespace='location_admin')),    


    path('category/', include(([
        path('', category.CategoryListView.as_view(), name='category_view'),
        path('create/', category.CategoryCreateView.as_view(), name='category_create'),
        path('update/<int:pk>/', category.CategoryUpdateView.as_view(), name='category_update'),
        path('delete/<int:pk>', category.CategoryDeleteView.as_view(), name='category_delete'),
    ], 'staff'), namespace='category_admin')),    


    path('question/', include(([
        path('', question.QuizListView.as_view(), name='quiz_change_list'),
        path('quiz/add/', question.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/results/view', question.results_view, name='results_view'),
        path('quiz/<int:pk>/', question.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', question.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', question.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', question.question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', question.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', question.QuestionDeleteView.as_view(), name='question_delete'),
        path('generate/', question.generate_report, name='generate_report'),
    ], 'staff'), namespace='question_admin')),

    # path('other/', other.other_staff, name='other_staff'),
    path('contact/', other.contact_staff, name='contact_staff'),


    # path('season/', include(([
    #     path('create/', season.SeasonCreateView.as_view(), name='season_create'),
    #     path('update/<int:pk>/', season.SeasonUpdateView.as_view(), name='season_update'),
    #     path('delete/<int:pk>/', season.SeasonDeleteView.as_view(), name='season_delete'),
    # ], 'staff'), namespace='season_admin')),

    # path('style/', include(([
    #     path('create/', style.StyleCreateView.as_view(), name='style_create'),
    #     path('update/<int:pk>/', style.StyleUpdateView.as_view(), name='style_update'),
    #     path('delete/<int:pk>/', style.StyleDeleteView.as_view(), name='style_delete'),
    # ], 'staff'), namespace='style_admin')),


    # path('landmark/', include(([
    #     path('create/', landmark.LandmarkCreateView.as_view(), name='landmark_create'),
    #     path('update/<int:pk>/', landmark.LandmarkUpdateView.as_view(), name='landmark_update'),
    #     path('delete/<int:pk>/', landmark.LandmarkDeleteView.as_view(), name='landmark_delete'),
    # ], 'staff'), namespace='landmark_admin')),


    path('contact/', include(([
        path('create/', contact.ContactCreateView.as_view(), name='contact_create'),
        path('update/<int:pk>/', contact.ContactUpdateView.as_view(), name='contact_update'),
        path('delete/<int:pk>/', contact.ContactDeleteView.as_view(), name='contact_delete'),
    ], 'staff'), namespace='contact_admin')),


     path('hotel/', include(([
     # path('', views.showhotels, name='showhotel'),
        path('', hotel.home, name='home'),

        path('hotel', hotel.showhotels, name='hotel_view'),
        path('hotel/create', hotel.HotelCreateView.as_view(), name='hotel_create'),
        path('hotel/update/(<pk>[0-9]+)', hotel.HotelUpdateView.as_view(), name='hotel_update'),
        path('hotel/delete/(<pk>[0-9]+)', hotel.HotelDeleteView.as_view(), name='hotel_delete'),

          # Bookings
        path('hotel/bookings/(<pk>[0-9]+)', hotel.showreservations, name='hotel_reservations'),
        path('hotel/bookings/delete/(<pk>[0-9]+)', hotel.cancelbooking, name='booking_remove'),
          
          
          # Room
        path('hotel/room/(<pk>[0-9]+)', hotel.managehotel, name='room_view'),
        path('hotel/rooms/create/(<pk>[0-9]+)', hotel.RoomCreateView.as_view(), name='room_create'),
        path('hotel/rooms/update/(<pk>[0-9]+)', hotel.RoomUpdateView.as_view(), name='room_update'),
        path('hotel/rooms/delete/(<pk>[0-9]+)', hotel.RoomDeleteView.as_view(), name='room_delete'),
          
          # Photo
        path('hotel/photo/(<id>[0-9]+)', hotel.showphotodash, name='photo_view'),
        path('hotel/photo/upload(<id>[0-9]+)', hotel.BasicUploadView.as_view(), name='photo_upload'),
        path('hotel/photo/delete/(<id>[0-9]+)', hotel.deletePhoto, name='photo_delete'),
        path('hotel/photo/thumbnail(<id>[0-9]+)', hotel.editThumbnail, name='editThumb'),

          # Chart
        path('charts/(<id>[0-9]+)/', hotel.ChartView.as_view(), name = 'partner_charts'),
        path('chart/data/(<id>[0-9]+)/', hotel.ChartData.as_view()),


        path('zxc', partner.displayDash, name='displayDash'),

        path('partners', partner.showPartners, name='showpartners'),
        path('partners/remove/(<id>[0-9]+)', partner.removePartner, name='removepartner'),

        path('proposals', partner.showProposals, name='showproposals'),
        path('proposals/accept/(<id>[0-9]+)', partner.acceptProposals, name='acceptproposal'),
        path('proposals/decline/(<id>[0-9]+)', partner.declineProposals, name='declineproposal'),
        
        path('partner/checkstatus', partner.checkstatus, name='proposal_check'),
    
     ], 'staff'), namespace='hotel_admin')),

]

travel/travel/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from general.views import home_view

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
	must_authenticate_view,
)

from question.views import question, active
from staff.views import staff 




urlpatterns = [

    path('api/', include('api.urls')),

    path('login/', login_view, name="login"),
    # path('logout/', logout_view, name="logout"),
	path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),


    path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/signup/', question.SignUpView.as_view(), name='signup'),
    path('accounts/signup/active/', active.ActiveSignUpView.as_view(), name='active_signup'),
    path('accounts/signup/staff/', staff.StaffSignUpView.as_view(), name='staff_signup'),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    
] 
urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),


    path('', home_view, name="home"),
    path('', include('api.urls')),
    path('blog/', include('blog.urls', 'blog')),
    path('trip/', include('trip.urls'), name='trip'),
    path('location/', include('location.urls'), name='location'),
    path('question/', include('question.urls')),
    path('contact/', include('general.urls')),
    path('hotel/', include('hotel.urls'), name="hotel"),
    path('account/', account_view, name="account"),
    path('staff/', include('staff.urls'), name="staff"),

)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travel/trip/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

from trip import views

app_name = 'trip'

urlpatterns = [
    

	path('trip_location/', views.trip_location, name="trip_location"),
	path('trip_summary/', views.trip_summary, name="trip_summary"),
	path('update_item/', views.updateItem, name="update_item"),
	path('trip_process/', views.trip_process, name="process_order"),


	path('my_trip/', views.myTrip, name="my_trip"),


    # path('person/', views.PersonCreate, name='trip_person_create'),
    # path('person/save', views.person_save, name='person_save'),
    # path('ajax/load-locations/', views.load_locations, name='ajax_load_locations'),
   
    path('system/', views.system_create, name='trip_system_create'),
    path('system/save/', views.trip_system_save, name='trip_system_save'),


    path('', views.trip_view, name='trip_list'),
    path('search/', views.search, name='search'),
    path('detail/<str:token>/', views.trip_detail, name='trip_detail'),
    path('tag/<slug:slug>/', views.tagged, name="tagged"),
    path('load-map/<str:token>/', views.load_map, name='load_map'),
]

travel/templates/snippets/footer_1.html
<!-- ========================== Footer ========================== -->
<footer id="footer">
	<div class="footer-top">
		<div class="container">
			<div class="copyright">
				&copy; Copyright <strong><span>Serenity</span></strong>. All Rights Reserved
			</div>
			<div class="credits">
				<!-- All the links in the footer should remain intact. -->
				<!-- You can delete the links only if you purchased the pro version. -->
				<!-- Licensing information: https://bootstrapmade.com/license/ -->
				<!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/serenity-bootstrap-corporate-template/ -->
				Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
			</div>
		</div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

travel/templates/snippets/footer_2.html
<!-- ========================== Footer ========================== -->
<footer class="footer">
	<div class="subfooter">
		<div class="container">
			<div class="row">
				<div class="span6">
					<p>
						&copy; Plato - All right reserved
					</p>
				</div>
				<div class="span6">
					<div class="pull-right">
						<div class="credits"> Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>

travel/templates/snippets/footer_3.html
<!-- ======= Footer ======= -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="copyright-footer">
                    <p class="copyright color-text-a">
                        &copy; Copyright
                        <span class="color-a">EstateAgency</span> All Rights Reserved.
                    </p>
                </div>
                <div class="credits">
                    <!--
            All the links in the footer should remain intact.
            You can delete the links only if you purchased the pro version.
            Licensing information: https://bootstrapmade.com/license/
            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=EstateAgency
          -->
                    Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                </div>
            </div>
        </div>
    </div>
</footer><!-- End  Footer -->

travel/templates/snippets/footer_admin.html
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

travel/templates/snippets/header_1.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!-- Header -->
<!-- <div class="search-bar mt-sm-2 mr-2">
		<form method="get">
			<input class="form-control" type="text" name="q" id="id_q" placeholder="Search...">
		</form>
</div> -->

<!-- End Header -->
<!-- 
<script type="text/javascript">
	document.getElementById("id_q").value = "{{query}}"
</script> -->



<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
	<div class="container d-flex">

		<div class="logo mr-auto">
			<h1 class="text-light"><a href="/">Travel JD</a></h1>
			<!-- Uncomment below if you prefer to use an image logo -->
			<!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
		</div>

		<nav class="nav-menu d-none d-lg-block">
			<ul>
				<li class="active"><a href="/">{% trans "Home" %}</a></li>
				<li><a href="{% url 'location:location_list' %}">{% trans "Tourist attraction" %}</a></li>
				<li><a href="{% url 'trip:trip_list' %}">{% trans "All Trip" %}</a></li>
				<li><a href="{% url 'home_hotel' %}">{% trans "Hotel" %}</a></li>
				<li><a href="{% url 'blog:home' %}">{% trans "Blog" %}</a></li>
				<li><a href="{% url 'general:contact_view' %}">{% trans "Contact" %}</a></li>
				<li class="drop-down"><a>{% trans "Language" %}</a>
					<ul>
						{% if LANGUAGE_CODE == 'en' %}
						<a href="{% url 'api:change-language' language='th' %}">{% trans "Thai" %}</a>
						{% else %}
						<a href="{% url 'api:change-language' language='en' %}">{% trans "English" %}</a>
						{% endif %}
					</ul>
				</li>

				{% if request.user.is_authenticated %}
				<li class="drop-down"><a>{% trans "Hello" %}, {{ request.user.username }}</a>
					<ul>
						<li><a href="{% url 'account' %}">{% trans "Account" %}</a></li>
						<li><a href="{% url 'reservation:bookings_view'%}">{% trans "My Booking" %}</a></li>
						<li><a href="{% url 'trip:my_trip'%}">{% trans "My Trip" %}</a></li>
						{% if request.user.is_staff %}
						<li><a href="{% url 'home_admin' %}">{% trans "Staff" %}</a></li>
						{% else %}
						<li><a href="{% url 'active:quiz_list' %}">{% trans "Question" %}</a></li>
						{% endif %}
						<li><a href="{% url 'logout' %}">{% trans "Longout" %}</a></li>
					</ul>
				</li>
				{% else %}
				<li><a href="{% url 'login' %}">{% trans "Sing In" %}</a></li>
				<li><a class="btn btn-outline-primary" href="{% url 'active_signup' %}">{% trans "Sing Up" %}</a></li>
				<!-- <li class="get-started"><a href="{% url 'active_signup' %}">{% trans "Sing Up" %}</a></li> -->
				<!-- <li><a class="btn btn-outline-primary" href="{% url 'register' %}">ลงทะเบียน</a></li> -->
				{% endif %}
				<li><a href="{% url 'trip:trip_location' %}">
					{% trans "Create Trip" %}<img  id="cart-icon" src="{% static 'images/travel.png' %}">
				</a></li>
				<li><p id="cart-total">{{ request.session.countTime }}</p></li>
			</ul>
		</nav>
		<!-- .nav-menu -->
	</div>

</header>
<!-- End Header -->

travel/templates/snippets/header_2.html
<header>
	<!-- ========================== Navbar ========================== -->
	<div class=" cbp-af-header">
		<div class=" cbp-af-inner">
			<div class="container">
				<div class="row">

					<div class="span4">
						<!-- logo -->
						<a class="logo" href="index.html">
							<h1>Plato</h1>
							<!-- <img src="assets/img/logo.png" alt="" /> -->
						</a>
						<!-- end logo -->
					</div>

					<div class="span8">
						<!-- top menu -->
						<div class="navbar">
							<div class="navbar-inner">
								<nav>
									<ul class="nav topnav">
										<li class="dropdown">
											<a href="/">Home</a>
										</li>
										<li class="dropdown">
											<a href="#">Features</a>
											<ul class="dropdown-menu">
												<li><a href="scaffolding.html">Scaffolding</a></li>
												<li><a href="base-css.html">Base CSS</a></li>
												<li><a href="components.html">Components</a></li>
												<li><a href="icons.html">Icons</a></li>
												<li><a href="list.html">Styled lists</a></li>
												<li class="dropdown"><a href="#">3rd level</a>
													<ul class="dropdown-menu sub-menu">
														<li><a href="#">Example menu</a></li>
														<li><a href="#">Example menu</a></li>
														<li><a href="#">Example menu</a></li>
													</ul>
												</li>
											</ul>
										</li>
										<li class="dropdown active">
											<a href="#">Pages</a>
											<ul class="dropdown-menu">
												<li><a href="about.html">About us</a></li>
												<li><a href="pricingtable.html">Pricing table</a></li>
												<li><a href="404.html">404</a></li>
											</ul>
										</li>
										<li class="dropdown">
											<a href="#">Portfolio</a>
											<ul class="dropdown-menu">
												<li><a href="portfolio-2cols.html">Portfolio 2 columns</a></li>
												<li><a href="portfolio-3cols.html">Portfolio 3 columns</a></li>
												<li><a href="portfolio-4cols.html">Portfolio 4 columns</a></li>
												<li><a href="portfolio-detail.html">Portfolio detail</a></li>
											</ul>
										</li>
										<li class="dropdown">
											<a href="#">Blog</a>
											<ul class="dropdown-menu">
												<li><a href="blog_left_sidebar.html">Blog left sidebar</a></li>
												<li><a href="blog_right_sidebar.html">Blog right sidebar</a></li>
												<li><a href="post_left_sidebar.html">Post left sidebar</a></li>
												<li><a href="post_right_sidebar.html">Post right sidebar</a></li>
											</ul>
										</li>
										<li>
											<a href="{% url 'contact' %}">Contact</a>
										</li>
									</ul>
								</nav>
							</div>
						</div>
						<!-- end menu -->
					</div>

				</div>
			</div>
		</div>
	</div>
</header>

travel/templates/snippets/sidebar_admin.html
{% load i18n %}
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'home_admin' %}">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">{% trans "Staff" %}<sup>{% trans "control" %}</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'home_admin' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>{% trans "Dashboard" %}</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Part1
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
            aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>{% trans "Hotel" %}</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">{% trans "Hotel" %}:</h6>
                <!-- <a class="collapse-item" href="{% url 'hotel_admin:home' %}">{% trans "Menu" %}</a> -->
                <a class="collapse-item" href="{% url 'hotel_admin:hotel_view' %}">{% trans "Hotel" %}</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>{% trans "Question" %}</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">{% trans "Question" %}:</h6>
                <a class="collapse-item" href="{% url 'question_admin:quiz_change_list' %}">{% trans "Question" %}</a>
                <!-- <a class="collapse-item" href="{% url 'question_admin:results_view' %}">{% trans "Anwser" %}</a> -->
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        {% trans "Part2" %}
    </div>

    <!-- Nav Item - Category -->
    <li class="nav-item">
        <a class="nav-link" href="{% url 'category_admin:category_view' %}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>{% trans "Category" %}</span></a>
    </li>

    <!-- Nav Item - Location -->
    <li class="nav-item">
        <a class="nav-link" href="{% url 'location_admin:location_view' %}">
            <i class="fas fa-fw fa-table"></i>
            <span>{% trans "Location" %}</span></a>
    </li>

    <!-- Nav Item - Location -->
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contact_staff' %}">
            <i class="fas fa-fw fa-table"></i>
            <span>{% trans "Contact" %}</span></a>
    </li>


    <!-- Nav Item - Pages Collapse Menu -->
    {% comment %} <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
            aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>{% trans "Other" %}</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <!-- <h6 class="collapse-header">Login Screens:</h6> -->
                <a class="collapse-item" href="{% url 'other_staff' %}">ฤดู</a>
                <a class="collapse-item" href="{% url 'other_staff' %}">จุดสนใจ</a>
                <a class="collapse-item" href="{% url 'other_staff' %}">รูปแบบ</a>
                <div class="collapse-divider"></div>
            </div>
        </div>
    </li> {% endcomment %}

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->